export const wordList = [
  "Foil characters",
  "Jealous sisters",
  "Self-preservation",
  "Revenge",
  "Hero's Journey",
  "Harmony",
  "Child murder",
  "Fertility",
  "Creation",
  "Impossible quest",
  "Marvel",
  "Tragedy",
  "Monstrous birth",
  "Situational irony",
  "Affair",
  "Aloofness",
  "3 ____",
  "Prophecy",
  "Deceit",
  "Malmaritata",
  "New world",
  "Dangerous sea",
  "Katabasis",
  "Enchantment",
  "Anthropomorphism",
  "Misfortune",
  "Supernatural",
  "Good fortune",
  "Bed trick",
  "Allegorical characters",
  "Bildungsroman",
  "Betrayal",
  "Tranformation",
  "Evil stepmother",
  "Fairies",
] as const;
